src/Feature/Accounts/code/Models/EditProfile.cs
namespace Sitecore.Feature.Accounts.Models
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Sitecore.Foundation.Dictionary.Repositories;

    public class EditProfile
    {
        [Display(Name = nameof(EmailCaption), ResourceType = typeof(EditProfile))]
        public string Email { get; set; }

        [Display(Name = nameof(FirstNameCaption), ResourceType = typeof(EditProfile))]
        public string FirstName { get; set; }

        [Display(Name = nameof(LastNameCaption), ResourceType = typeof(EditProfile))]
        public string LastName { get; set; }

        [Display(Name = nameof(PhoneNumberCaption), ResourceType = typeof(EditProfile))]
        [RegularExpression(@"^\+?\d*(\(\d+\)-?)?\d+(-?\d+)+$", ErrorMessageResourceName = nameof(PhoneNumberFormat), ErrorMessageResourceType = typeof(EditProfile))]
        [MaxLength(20, ErrorMessageResourceName = nameof(MaxLengthExceeded), ErrorMessageResourceType = typeof(EditProfile))]
        public string PhoneNumber { get; set; }

        [Display(Name = nameof(InterestsCaption), ResourceType = typeof(EditProfile))]
        public string Interest { get; set; }

        public IEnumerable<string> InterestTypes { get; set; }

        public static string EmailCaption => DictionaryPhraseRepository.Current.Get("/Accounts/Edit Profile/Email", "E-mail");
        public static string FirstNameCaption => DictionaryPhraseRepository.Current.Get("/Accounts/Edit Profile/First Name", "First name");
        public static string LastNameCaption => DictionaryPhraseRepository.Current.Get("/Accounts/Edit Profile/Last Name", "Last name");
        public static string PhoneNumberCaption => DictionaryPhraseRepository.Current.Get("/Accounts/Edit Profile/Phone Number", "Phone number");
        public static string InterestsCaption => DictionaryPhraseRepository.Current.Get("/Accounts/Edit Profile/Interests", "Interests");
        public static string MaxLengthExceeded => DictionaryPhraseRepository.Current.Get("/Accounts/Edit Profile/Max Length", "{0} length should be less than {1}");
        public static string PhoneNumberFormat => DictionaryPhraseRepository.Current.Get("/Accounts/Edit Profile/Phone Number Format", "Phone number should contain only +, ( ) and digits");
    }
}

src/Feature/Accounts/code/Controllers/AccountsController.cs
namespace Sitecore.Feature.Accounts.Controllers
{
    using System;
    using System.Web.Mvc;
    using System.Web.Security;
    using Sitecore.Diagnostics;
    using Sitecore.Feature.Accounts.Attributes;
    using Sitecore.Feature.Accounts.Models;
    using Sitecore.Feature.Accounts.Repositories;
    using Sitecore.Feature.Accounts.Services;
    using Sitecore.Foundation.Alerts.Extensions;
    using Sitecore.Foundation.Alerts.Models;
    using Sitecore.Foundation.Dictionary.Repositories;
    using Sitecore.Foundation.SitecoreExtensions.Attributes;
    using Sitecore.Foundation.SitecoreExtensions.Extensions;
    using Sitecore.Foundation.SitecoreExtensions.Services;

    public class AccountsController : Controller
    {
        private readonly IAccountRepository accountRepository;
        private readonly INotificationService notificationService;
        private readonly IAccountsSettingsService accountsSettingsService;
        private readonly IGetRedirectUrlService getRedirectUrlService;
        private readonly IUserProfileService userProfileService;
        private readonly IContactProfileService contactProfileService;

        public AccountsController() : this(new AccountRepository(new AccountTrackerService(new AccountsSettingsService(), new TrackerService())), new NotificationService(new AccountsSettingsService()), new AccountsSettingsService(), new GetRedirectUrlService(), new UserProfileService(), new ContactProfileService())
        {
        }

        public AccountsController(IAccountRepository accountRepository, INotificationService notificationService, IAccountsSettingsService accountsSettingsService, IGetRedirectUrlService getRedirectUrlService, IUserProfileService userProfileService, IContactProfileService contactProfileService)
        {
            this.accountRepository = accountRepository;
            this.notificationService = notificationService;
            this.accountsSettingsService = accountsSettingsService;
            this.getRedirectUrlService = getRedirectUrlService;
            this.userProfileService = userProfileService;
            this.contactProfileService = contactProfileService;
        }


        [RedirectAuthenticated]
        public ActionResult Register()
        {
            return this.View();
        }

        public static string UserAlreadyExistsError => DictionaryPhraseRepository.Current.Get("/Accounts/Register/User Already Exists", "A user with specified e-mail address already exists");

        [HttpPost]
        [ValidateModel]
        [RedirectAuthenticated]
        [ValidateRenderingId]
        public ActionResult Register(RegistrationInfo registrationInfo)
        {
            if (this.accountRepository.Exists(registrationInfo.Email))
            {
                this.ModelState.AddModelError(nameof(registrationInfo.Email), UserAlreadyExistsError);

                return this.View(registrationInfo);
            }

            try
            {
                this.accountRepository.RegisterUser(registrationInfo.Email, registrationInfo.Password, this.userProfileService.GetUserDefaultProfileId());
                this.contactProfileService?.SetPreferredEmail(registrationInfo.Email);

                var link = this.getRedirectUrlService.GetRedirectUrl(AuthenticationStatus.Authenticated);
                return this.Redirect(link);
            }
            catch (MembershipCreateUserException ex)
            {
                Log.Error($"Can't create user with {registrationInfo.Email}", ex, this);
                this.ModelState.AddModelError(nameof(registrationInfo.Email), ex.Message);

                return this.View(registrationInfo);
            }
        }

        [RedirectAuthenticated]
        public ActionResult Login(string returnUrl = null)
        {
            var loginInfo = new LoginInfo
                            {
                                ReturnUrl = returnUrl
                            };
            return this.View(loginInfo);
        }

        public ActionResult LoginTeaser()
        {
            return this.View();
        }

        [HttpPost]
        [ValidateModel]
        [ValidateRenderingId]
        public ActionResult Login(LoginInfo loginInfo)
        {
            return this.Login(loginInfo, redirectUrl => new RedirectResult(redirectUrl));
        }

        protected virtual ActionResult Login(LoginInfo loginInfo, Func<string, ActionResult> redirectAction)
        {
            var user = this.accountRepository.Login(loginInfo.Email, loginInfo.Password);
            if (user == null)
            {
                this.ModelState.AddModelError("invalidCredentials", DictionaryPhraseRepository.Current.Get("/Accounts/Login/User Not Found", "Username or password is not valid."));
                return this.View(loginInfo);
            }

            if (!this.userProfileService.ValidateUser(user))
            {
                this.accountRepository.Logout();
                this.ModelState.AddModelError("invalidCredentials", DictionaryPhraseRepository.Current.Get("/Accounts/Login/Invalid User", "Sorry, your user details cannot be used on this website."));
                return this.View(loginInfo);
            }
            var redirectUrl = loginInfo.ReturnUrl;
            if (string.IsNullOrEmpty(redirectUrl))
            {
                redirectUrl = this.getRedirectUrlService.GetRedirectUrl(AuthenticationStatus.Authenticated);
            }

            return redirectAction(redirectUrl);
        }

        [HttpPost]
        [ValidateModel]
        public ActionResult _Login(LoginInfo loginInfo)
        {
            return this.Login(loginInfo, redirectUrl => this.Json(new LoginResult
                                                                  {
                                                                      RedirectUrl = redirectUrl
                                                                  }));
        }

        [HttpPost]
        [ValidateModel]
        public ActionResult LoginTeaser(LoginInfo loginInfo)
        {
            return this.Login(loginInfo, redirectUrl => new RedirectResult(redirectUrl));
        }

        [HttpPost]
        public ActionResult Logout()
        {
            this.accountRepository.Logout();

            return this.Redirect(Context.Site.GetRootItem().Url());
        }

        private static string ForgotPasswordEmailNotConfigured => DictionaryPhraseRepository.Current.Get("/Accounts/Forgot Password/Email Not Configured", "The Forgot Password E-mail has not been configured");

        [RedirectAuthenticated]
        public ActionResult ForgotPassword()
        {
            try
            {
                this.accountsSettingsService.GetForgotPasswordMailTemplate();
            }
            catch (Exception)
            {
                return this.InfoMessage(InfoMessage.Error(ForgotPasswordEmailNotConfigured));
            }

            return this.View();
        }

        private static string UserDoesNotExistError => DictionaryPhraseRepository.Current.Get("/Accounts/Forgot Password/User Does Not Exist", "User with specified e-mail address does not exist");

        [HttpPost]
        [ValidateModel]
        [RedirectAuthenticated]
        public ActionResult ForgotPassword(PasswordResetInfo model)
        {
            if (!this.accountRepository.Exists(model.Email))
            {
                this.ModelState.AddModelError(nameof(model.Email), UserDoesNotExistError);

                return this.View(model);
            }

            try
            {
                var newPassword = this.accountRepository.RestorePassword(model.Email);
                this.notificationService.SendPassword(model.Email, newPassword);
                return this.InfoMessage(InfoMessage.Success(DictionaryPhraseRepository.Current.Get("/Accounts/Forgot Password/Reset Password Success", "Your password has been reset.")));
            }
            catch (Exception ex)
            {
                Log.Error($"Can't reset password for user {model.Email}", ex, this);
                this.ModelState.AddModelError(nameof(model.Email), ex.Message);

                return this.View(model);
            }
        }

        [RedirectUnauthenticated]
        public ActionResult EditProfile()
        {
            if (!Context.PageMode.IsNormal)
            {
                return this.View(this.userProfileService.GetEmptyProfile());
            }

            if (!this.userProfileService.ValidateUser(Context.User))
            {
                return this.ProfileMismatchMessage;
            }

            var profile = this.userProfileService.GetProfile(Context.User.Profile);

            return this.View(profile);
        }

        [HttpPost]
        [RedirectUnauthenticated]
        public virtual ActionResult EditProfile(EditProfile profile)
        {
            if (this.userProfileService.GetUserDefaultProfileId() != Context.User.Profile.ProfileItemId)
            {
                return this.ProfileMismatchMessage;
            }

            if (!this.userProfileService.ValidateProfile(profile, this.ModelState))
            {
                profile.InterestTypes = this.userProfileService.GetInterests();
                return this.View(profile);
            }

            this.userProfileService.SetProfile(Context.User.Profile, profile);
            this.contactProfileService?.SetProfile(profile);

            this.Session["EditProfileMessage"] = new InfoMessage(DictionaryPhraseRepository.Current.Get("/Accounts/Edit Profile/Edit Profile Success", "Profile was successfully updated"));
            return this.Redirect(this.Request.RawUrl);
        }

        private ViewResult ProfileMismatchMessage
        {
            get
            {

src/Feature/Accounts/code/Views/Accounts/AccountsMenu.cshtml
@using Sitecore.Feature.Accounts
@using Sitecore.Feature.Accounts.Models
@using Sitecore.Feature.Accounts.Services
@using Sitecore.Foundation.Dictionary.Extensions
@model Sitecore.Mvc.Presentation.RenderingModel

@{
  if (Model.Item == null)
  {
    return;
  }
  var accountSettings = AccountsSettingsService.Instance.GetAccountsSettingsItem(Model.Item);
  if (accountSettings == null)
  {
    return;
  }
}
  <li class="dropdown hidden-xs">
    <a href="#" class="btn dropdown-toggle" data-toggle="dropdown">
      <i class="fa fa-user"></i>
    </a>
    <div class="dropdown-menu">
      @if (!(Sitecore.Context.IsLoggedIn && Sitecore.Context.PageMode.IsNormal))
      {
        <h4>@Html.Sitecore().DictionaryField("/Accounts/Accounts Menu/Login", "Login")</h4>
        <form id="loginModal">
          @Html.Partial("~/Views/Accounts/_Login.cshtml", new LoginInfo())
        </form>
      }
      else
      {
        using (Html.BeginForm("Logout", "Accounts", FormMethod.Post))
        {
          if (!string.IsNullOrWhiteSpace(Sitecore.Context.User.Profile.FullName))
          {
            <div class="form-group">
              <label class="control-label">@Html.Sitecore().DictionaryField("/Accounts/Accounts Menu/Email", "Name")</label>
              <div class="form-control-static">@Sitecore.Context.User.Profile.FullName</div>
            </div>
          }
          <div class="form-group">
            <label class="control-label">@Html.Sitecore().DictionaryField("/Accounts/Accounts Menu/Email", "E-mail")</label>
            <div class="form-control-static">@Sitecore.Context.User.Profile.Email</div>
          </div>
          <a class="btn btn-block btn-primary" href="@AccountsSettingsService.Instance.GetPageLinkOrDefault(Model.Item, Templates.AccountsSettings.Fields.AccountsDetailsPage)">@Html.Sitecore().DictionaryField("/Accounts/Accounts Menu/Edit Details", "Edit details")</a>
          <button type="submit" class="btn btn-block btn-default">@Html.Sitecore().Dictionary("/Accounts/Accounts Menu/Logout", "Logout")</button>
        }
      }
    </div>
  </li>

src/Feature/Accounts/code/Views/Accounts/EditProfile.cshtml
@using Sitecore.Foundation.Alerts
@using Sitecore.Foundation.Alerts.Models
@using Sitecore.Foundation.Dictionary.Extensions
@using Sitecore.Foundation.SitecoreExtensions.Extensions
@using Sitecore.Mvc.Configuration
@model Sitecore.Feature.Accounts.Models.EditProfile

@using (Html.BeginRouteForm(MvcSettings.SitecoreRouteName, FormMethod.Post, new
                                                                            {
                                                                                @class = "form-signin"
                                                                            }))
{
    @Html.AddUniqueFormId()
    var info = Session.GetAndRemove("EditProfileMessage") as InfoMessage;
    if (info != null)
    {
        Html.RenderPartial(Constants.InfoMessageView, info);
    }

    <div class="form-group has-feedback">
        @Html.LabelFor(x => x.Email, new
                                     {
                                         @class = "control-label"
                                     })

        @Html.TextBoxFor(x => x.Email, new
                                       {
                                           @class = "form-control",
                                           id = "email",
                                           @readonly = true
                                       })
        <span class="glyphicon glyphicon-lock form-control-feedback" aria-hidden="true"></span>
    </div>

    <div class="form-group @Html.ValidationErrorFor(x => x.FirstName, "has-error")">
        @Html.LabelFor(x => x.FirstName, new
                                         {
                                             @class = "control-label"
                                         })

        @Html.TextBoxFor(x => x.FirstName, new
                                           {
                                               @class = "form-control",
                                               id = "firstName",
                                               placeholder = Html.Sitecore().Dictionary("/Accounts/Edit Profile/Edit Profile First Name Placeholder", "Please enter your first name")
                                           })

        @Html.ValidationMessageFor(x => x.FirstName, "", new
                                                         {
                                                             @class = "help-block"
                                                         }, "p")
    </div>

    <div class="form-group @Html.ValidationErrorFor(x => x.LastName, "has-error")">
        @Html.LabelFor(x => x.LastName, new
                                        {
                                            @class = "control-label"
                                        })

        @Html.TextBoxFor(x => x.LastName, new
                                          {
                                              @class = "form-control",
                                              id = "lastName",
                                              placeholder = Html.Sitecore().Dictionary("/Accounts/Edit Profile/Edit Profile Last Name Placeholder", "Please enter your last name")
                                          })

        @Html.ValidationMessageFor(x => x.LastName, "", new
                                                        {
                                                            @class = "help-block"
                                                        }, "p")
    </div>

    <div class="form-group @Html.ValidationErrorFor(x => x.PhoneNumber, "has-error")">
        @Html.LabelFor(x => x.PhoneNumber, new
                                           {
                                               @class = "control-label"
                                           })

        @Html.TextBoxFor(x => x.PhoneNumber, new
                                             {
                                                 @class = "form-control",
                                                 id = "phoneNumber",
                                                 placeholder = Html.Sitecore().Dictionary("/Accounts/Edit Profile/Edit Profile Phone Placeholder", "Please enter your contact phone number")
                                             })

        @Html.ValidationMessageFor(x => x.PhoneNumber, "", new
                                                           {
                                                               @class = "help-block"
                                                           }, "p")
    </div>

    <div class="form-group @Html.ValidationErrorFor(x => x.Interest, "has-error")">
        @Html.LabelFor(x => x.Interest, new
                                        {
                                            @class = "control-label"
                                        })

        @Html.DropDownListFor(x => x.Interest, new SelectList(Model.InterestTypes), "", new
                                                                                        {
                                                                                            @class = "form-control",
                                                                                            id = "interests"
                                                                                        })

        @Html.ValidationMessageFor(x => x.Interest, "", new
                                                        {
                                                            @class = "help-block"
                                                        }, "p")
    </div>

    <input type="submit" class="btn btn-primary btn-lg btn-block" value="@Html.Sitecore().DictionaryField("/Accounts/Edit Profile/Update", "Update")"/>
}

src/Feature/Accounts/code/Views/Accounts/ForgotPassword.cshtml
@using Sitecore.Foundation.Dictionary.Extensions
@using Sitecore.Foundation.SitecoreExtensions.Extensions
@using Sitecore.Mvc.Configuration
@model Sitecore.Feature.Accounts.Models.PasswordResetInfo

@using (Html.BeginRouteForm(MvcSettings.SitecoreRouteName, FormMethod.Post, new { @class = "form-signin" }))
{
  @Html.Sitecore().FormHandler()
  <div class="form-group @Html.ValidationErrorFor(x => x.Email, "has-error")">
    @Html.LabelFor(x => x.Email, new
{
  @class = "control-label"
})

    @Html.TextBoxFor(x => x.Email, new
                                   {
                                     @class = "form-control",
                                     id = "registerEmail",
                                     @placeholder = Html.Sitecore().Dictionary("/Accounts/Forgot Password/Forgot Password Email Placeholder", "Please enter the e-mail address you used to register")
                                   })
    @Html.ValidationMessageFor(x => x.Email, "", new { @class = "help-block" }, "p")

  </div>

  <input type="submit" class="btn btn-primary btn-lg btn-block" value="@Html.Sitecore().Dictionary("/Accounts/Forgot Password/Reset Password", "Reset password")" />
  <div class="help-block">@Html.Sitecore().DictionaryField("/Accounts/Forgot Password/Reset Password Info", "The new password will be sent to your e-mail.")</div>
}

src/Feature/Accounts/code/Views/Accounts/Login.cshtml
@using Sitecore.Feature.Accounts
@using Sitecore.Feature.Accounts.Services
@using Sitecore.Foundation.Dictionary.Extensions
@using Sitecore.Foundation.SitecoreExtensions.Extensions
@using Sitecore.Mvc.Configuration
@model Sitecore.Feature.Accounts.Models.LoginInfo

@using (Html.BeginRouteForm(MvcSettings.SitecoreRouteName, FormMethod.Post, new { @class = "form-signin" }))
{
    @Html.Hidden("ReturnUrl", Model.ReturnUrl)
    @Html.AddUniqueFormId()
    @Html.ValidationSummary(true)
    <div class="form-group @Html.ValidationErrorFor(x => x.Email, "has-error")">
        @Html.LabelFor(x => x.Email, new
                                     {
                                         @class = "control-label"
                                     })
        @Html.TextBoxFor(x => x.Email, new
                                       {
                                           @class = "form-control",
                                           id = "loginEmail",
                                           placeholder = Html.Sitecore().Dictionary("/Accounts/Login/Login E-mail Placeholder", "Enter your e-mail")
                                       })
        @Html.ValidationMessageFor(x => x.Email, "", new
                                                     {
                                                         @class = "help-block"
                                                     }, "p")
    </div>
    <div class="form-group @Html.ValidationErrorFor(x => x.Password, "has-error")">
        @Html.LabelFor(x => x.Password, new
                                        {
                                            @class = "control-label"
                                        })
        @Html.PasswordFor(x => x.Password, new
                                           {
                                               @class = "form-control",
                                               id = "loginPassword",
                                               placeholder = Html.Sitecore().Dictionary("/Accounts/Login/Login Password Placeholder", "Enter your password")
                                           })
        @Html.ValidationMessageFor(x => x.Password, "", new
                                                        {
                                                            @class = "help-block"
                                                        }, "p")
    </div>
    @Html.ValidationMessage("invalidCredentials", new
                                                  {
                                                      @class = "alert alert-danger"
                                                  }, "div")
    <div class="row">
        <div class="col-lg-6">
            <input type="submit" class="btn btn-primary btn-lg btn-block" value="@Html.Sitecore().Dictionary("/Accounts/Login/Login", "Login")"/>
        </div>
        <div class="col-lg-6">
            <a href="@AccountsSettingsService.Instance.GetPageLinkOrDefault(Sitecore.Context.Item, Templates.AccountsSettings.Fields.RegisterPage)" class="btn btn-default btn-lg btn-block">@Html.Sitecore().DictionaryField("/Accounts/Login/Register", "Register")</a>
        </div>
    </div>
    <a href="@AccountsSettingsService.Instance.GetPageLinkOrDefault(Sitecore.Context.Item, Templates.AccountsSettings.Fields.ForgotPasswordPage)" class="btn btn-link">@Html.Sitecore().DictionaryField("/Accounts/Login/Forgot Your Password", "Forgot your password?")</a>
}

src/Feature/Accounts/code/Views/Accounts/LoginTeaser.cshtml
@using Sitecore.Feature.Accounts
@using Sitecore.Feature.Accounts.Services
@using Sitecore.Foundation.Dictionary.Extensions
@using Sitecore.Foundation.SitecoreExtensions.Extensions
@using Sitecore.Foundation.Theming.Extensions
@using Sitecore.Mvc
@model Sitecore.Feature.Accounts.Models.LoginInfo

@{
    var item = Html.Sitecore().CurrentItem;
    var titleField = Templates.LoginTeaser.Fields.Title;
    var summaryField = Templates.LoginTeaser.Fields.Summary;
    var isLoggedIn = Sitecore.Context.IsLoggedIn && Sitecore.Context.PageMode.IsNormal;
    if (isLoggedIn)
    {
        titleField = Templates.LoginTeaser.Fields.LoggedInTitle;
        summaryField = Templates.LoginTeaser.Fields.LoggedInSummary;
    }
}

<div class="well @Html.Sitecore().CurrentRendering.GetBackgroundClass()">
    @if (item.FieldHasValue(titleField) || Sitecore.Context.PageMode.IsExperienceEditor)
    {
        <h4>
            @Html.Sitecore().Field(titleField, item)
        </h4>
    }

    @if (item.FieldHasValue(summaryField) || Sitecore.Context.PageMode.IsExperienceEditor)
    {
        <p>
            @Html.Sitecore().Field(summaryField, item, new { linebreaks = "<br/>" })
        </p>
    }

    @if (Sitecore.Context.PageMode.IsExperienceEditor)
    {
        <div class="well bg-info">
            <label>
                @Html.Sitecore().Dictionary("/Accounts/Login/Logged In Fields Description", "These fields are shown when the user is logged in.")
            </label>
            <h4>
                @Html.Sitecore().Field(Templates.LoginTeaser.Fields.LoggedInTitle, item)
            </h4>
            <p>
                @Html.Sitecore().Field(Templates.LoginTeaser.Fields.LoggedInSummary, item, new
                                                                                           {
                                                                                               linebreaks = "<br/>"
                                                                                           })
            </p>
        </div>
    }

    @if (!isLoggedIn)
    {
        using (Html.BeginRouteForm(Sitecore.Mvc.Configuration.MvcSettings.SitecoreRouteName, FormMethod.Post, new { @class = "form-signin" }))
        {
            @Html.AddUniqueFormId()
            @Html.ValidationSummary(true)
            <div class="form-group @Html.ValidationErrorFor(x=>x.Email, "has-error")">
                @Html.TextBoxFor(x => x.Email, new { @class = "form-control", id = "loginEmail", @placeholder = Html.Sitecore().Dictionary("/Accounts/Login/Login E-mail Placeholder", "Enter your e-mail") })
                @Html.ValidationMessageFor(x => x.Email, "", new { @class = "help-block" }, "p")
            </div>
            <div class="form-group @Html.ValidationErrorFor(x=>x.Password, "has-error")">
                @Html.PasswordFor(x => x.Password, new { @class = "form-control", id = "loginPassword", @placeholder = Html.Sitecore().Dictionary("/Accounts/Login/Login Password Placeholder", "Enter your password") })
                @Html.ValidationMessageFor(x => x.Password, "", new { @class = "help-block" }, "p")
            </div>
            @Html.ValidationMessage("invalidCredentials", new { @class = "alert alert-danger" }, "div")
            <input type="submit" class="btn btn-primary btn-block" value="@Html.Sitecore().Dictionary("/Accounts/Login/Login", "Login")" />
            <a href="@AccountsSettingsService.Instance.GetPageLinkOrDefault(Sitecore.Context.Item, Templates.AccountsSettings.Fields.RegisterPage)" class="btn btn-link btn-block">@Html.Sitecore().DictionaryField("/Accounts/Login/Register", "Register")</a>
            <a href="@AccountsSettingsService.Instance.GetPageLinkOrDefault(Sitecore.Context.Item, Templates.AccountsSettings.Fields.ForgotPasswordPage)" class="btn btn-link btn-block">@Html.Sitecore().DictionaryField("/Accounts/Login/Forgot Your Password", "Forgot your password?")</a>
        }
    }
    else
    {
        using (Html.BeginForm("Logout", "Accounts", FormMethod.Post))
        {
            if (!string.IsNullOrWhiteSpace(Sitecore.Context.User.Profile.FullName))
            {
                <div class="form-group">
                    <label class="control-label">@Html.Sitecore().DictionaryField("/Accounts/Accounts Menu/Email", "Name")</label>
                    <div class="form-control-static">@Sitecore.Context.User.Profile.FullName</div>
                </div>
            }
            <div class="form-group">
                <label class="control-label">@Html.Sitecore().DictionaryField("/Accounts/Accounts Menu/Email", "E-mail")</label>
                <div class="form-control-static">@Sitecore.Context.User.Profile.Email</div>
            </div>
            <a class="btn btn-block btn-primary" href="@AccountsSettingsService.Instance.GetPageLinkOrDefault(item, Templates.AccountsSettings.Fields.AccountsDetailsPage)">@Html.Sitecore().DictionaryField("/Accounts/Accounts Menu/Edit Details", "Edit details")</a>
            <button type="submit" class="btn btn-block btn-default">@Html.Sitecore().Dictionary("/Accounts/Accounts Menu/Logout", "Logout")</button>
        }
    }
</div>